# docker-compose up
# docker-compose down
version: '3'
services:
  # https://hub.docker.com/_/mysql/
  mysql:
    # image: "mysql:8.0"
    image: "mysql:5.7"
    environment: 
      - MYSQL_ROOT_PASSWORD=mysqlpassword
      # TODO: it seems the user is just root...
    ports:
      # NOTE: need to remove local mysql https://askubuntu.com/questions/172514/how-do-i-uninstall-mysql
      - "3306:3306" # guest host
  # TODO: GUI, it suggests using adminer
  # TODO: does adminer support set envinroment to use default database?
  # host: mysql (not localhost!!!)
  adminer:
    image: "adminer"
    ports:
      - "8080:8080"