# docker-compose up
# docker-compose down
version: '3'
services:
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    # three flavors, the default, ships w/ X-Pack Basic features
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.3
    environment:
      - ELASTIC_PASSWORD=elasticsearchpassword
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.3
    ports:
      - "5601:5601"